//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VibeManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEMS
    {
        public int id { get; set; }
        public string name_item { get; set; }
        public int amount { get; set; }
        public int id_space { get; set; }
    
        public virtual SPACES SPACES { get; set; }
    }
}
