//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VibeManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MESSAGES
    {
        public int id { get; set; }
        public string context { get; set; }
        public System.DateTime send_at { get; set; }
        public int sender_id { get; set; }
        public int id_chat { get; set; }
    
        public virtual CHAT CHAT { get; set; }
        public virtual USERS USERS { get; set; }
    }
}
