//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VibeManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TICKETS
    {
        public int id { get; set; }
        public System.DateTime date { get; set; }
        public System.TimeSpan time { get; set; }
        public Nullable<int> num_col { get; set; }
        public Nullable<int> num_row { get; set; }
        public int id_event { get; set; }
        public int id_user { get; set; }
    
        public virtual EVENTS EVENTS { get; set; }
        public virtual USERS USERS { get; set; }
    }
}
